### ISSUE TITLE
Rename examples -> example

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/grpc-dart#18]
Per guidelines - https://www.dartlang.org/tools/pub/package-layout

**Comment by jakobr-google** [comment]
In this case, we'll have several examples, each in their own subdirectory of `examples/`. Should it still be renamed?

It doesn't look like the guidelines (or tooling for that matter) take into account that examples might be larger projects with their own pubspecs.

**Comment by kevmoo** [comment]
The guideline does say each example should be under it's own subdirectory.

Just trying to be consistent.

Supporting projects with their own pubspecs needs work, certainly...

**Comment by jakobr-google** [comment]
Ah, you're right. I'd missed that little bit of the guideline. :)
