### ISSUE TITLE
can't get anything to build

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/grpc-dart#36]
Keep getting this:
Your package must have a "web" directory,
or you must specify the source directories.

What am I doing wrong?
dart 1.24.2

**Comment by jakobr-google** [comment]
Depends. What are you doing?

**Comment by jakobr-google** [comment]
I'm guessing you're trying to run `pub build`? That's for web apps, so it won't work here.

The instructions in the README.md's in the examples should work. If not, please let me know.

**Comment by mit-mit** [comment]
Closing; @unicomp21 if you are still having issues, please reopen with additional inforation.
