### ISSUE TITLE
generate stub doesn't work

### ISSUE THREAD

**Issue by Kleak** [dart-lang/grpc-dart#37]
When i launch this command :
`protoc --dart_out=grpc:lib/src/generated -Iprotos protos/metadata.proto`
i got the following error :
```
protoc-gen-dart: program not found or is not executable
--dart_out: protoc-gen-dart: Plugin failed with status code 1.
```

i have installed everything (protoc and the protoc_plugin)

**Comment by jakobr-google** [comment]
The error indicates that you don't have protoc-gen-dart on your PATH. If you've installed it using `pub global activate protoc_plugin`, you'll also need to add `~/.pub-cache/bin` to PATH.

Alternatively, you can point protoc at the plugin by adding `--plugin=protoc-gen-dart=<full path to>/protoc-gen-dart` to the protoc command line.

**Comment by Kleak** [comment]
I can launch both from my terminal :/
Will try with the full path alternative

**Comment by jakobr-google** [comment]
What happens when you launch `protoc-gen-dart` directly? If everything works, it should "hang" (waiting for stdio input from protoc).

**Comment by Kleak** [comment]
it's exactly what happend the program is waiting for input

**Comment by jakobr-google** [comment]
Then you've got me stumped. What version of protoc do you have?

**Comment by Kleak** [comment]
`libprotoc 3.4.0`

**Comment by jakobr-google** [comment]
protoc 3.4.0 works for me, so that *should* be fine. Are there any spaces or other "weirdness" in the path to protoc-gen-dart? What OS are you running on?

If you can't get it to work using `pub global activate`, another alternative is to clone [dart-lang/dart-protoc-plugin](https://github.com/dart-lang/dart-protoc-plugin) and use `--plugin=protoc-gen-dart=<path/to/dart-protoc-plugin>/bin/protoc-gen-dart`.

**Comment by Kleak** [comment]
i have compile the source from the cpp release here https://github.com/google/protobuf/releases/tag/v3.4.0

**Comment by Kleak** [comment]
no weird spaces or other in my path `/home/kleak/.pub-cache/bin` for `protoc-gen-dart`
I'm running on linux

**Comment by jakobr-google** [comment]
Pretty similar setup to mine. What does `strace -f protoc --dart_out=...` say? Does protoc look for protoc-gen-dart in the right place?

**Comment by Kleak** [comment]
Ok i have found what is the problem
in my .profile i had and it does work.
```sh
PATH="$PATH:~/.pub-cache/bin"
```
i have change to
```sh
PATH="$PATH:/home/kleak/.pub-cache/bin"
```
and it work now :)

**Comment by jakobr-google** [comment]
Ah, yes. Looks like protoc doesn't do ~ expansion, so we need the full path in PATH.

I'll close this one, then. Thanks for confirming!

**Comment by Kleak** [comment]
yes problem solved :) thanks for the help

**Comment by ericbets** [comment]
If you come across this, try replacing all mentions of ~ in your $path to /home/yourname. That fixed it for me.
