### ISSUE TITLE
ChannelOptions.authority never used

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/grpc-dart#52]

**Comment by jakobr-google** [comment]
It's being used here: https://github.com/dart-lang/grpc-dart/blob/master/lib/src/client/connection.dart#L100

Both for the TLS handshake (https://github.com/dart-lang/grpc-dart/blob/master/lib/src/client/connection.dart#L113) and the HTTP Authority header (https://github.com/dart-lang/grpc-dart/blob/master/lib/src/client/connection.dart#L158).

Do you see any errors related to this?

**Comment by stevenroose** [comment]
Oh, sorry. I used the IntelliJ IDEA "find usages" feature and it didn't find anything, must be an error from them. No I don't use it, just thought it was forgotten about, wanted to report.
