### ISSUE TITLE
Implement cloud-to-prod-auth interop tests

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/grpc-dart#53]
As described in https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md.

We're missing these tests:
* compute_engine_creds
* jwt_token_creds
* oauth2_auth_token
* per_rpc_creds

(other language's interop clients also have a service_account_creds test, but I don't know if that one is required)

package:googleapis_auth has support for these, so they just need to be wired up.

**Comment by jtattermusch** [comment]
CC @jtattermusch
